### ISSUE TITLE
ShowHelpException not caught

### ISSUE THREAD

**Issue by passy** [xenomachina/kotlin-argparser#20]
Apologies if I'm misunderstanding something here, but from looking at the implementation it doesn't seem like anything is catching `com.xenomachina.argparser.ShowHelpException: Help was requested` and if I start my application with `-h` or `--help`, I see the exception stacktrace rather than the help text:

```
Exception in thread "main" com.xenomachina.argparser.ShowHelpException: Help was requested
        at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:590)
        at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:38)
        at com.xenomachina.argparser.OptionDelegate.parseOption(OptionDelegate.kt:60)
        at com.xenomachina.argparser.ArgParser.parseShortOpts(ArgParser.kt:576)
        at com.xenomachina.argparser.ArgParser.access$parseShortOpts(ArgParser.kt:38)
        at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:473)
        at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at com.xenomachina.argparser.ArgParser.getParseOptions(ArgParser.kt)
        at com.xenomachina.argparser.ArgParser.force(ArgParser.kt:447)
        at com.xenomachina.argparser.ParsingDelegate.getValue(ParsingDelegate.kt:39)
        at com.xenomachina.argparser.ArgParser$Delegate.getValue(ArgParser.kt:340)
        at myapp.TestRunnerArgs.getTests(testRunner.kt)
```

Is this expected? Do I need to catch this myself and delegate to the help formatter?

**Comment by passy** [comment]
Turns out I just cannot read. The [README](https://github.com/xenomachina/kotlin-argparser#error-handling) describes exactly this behavior. `mainBody` is what I wanted.

Sorry, I'll get a coffee now in hopes of this improving my reading comprehension. ☕️

**Comment by xenomachina** [comment]
If you have any ideas for how this could be made clearer in the docs, please let me know. Thanks!

**Comment by GinoHereIam** [comment]
Sorry, I've got same issue and can't figure out :D I didn't find anything in the README about this behavior. :(

**Comment by sifraser** [comment]
I didn't get it either.. but you need:
`fun main(args: Array<String>) = mainBody {
    <your code>
}`

**Comment by GinoHereIam** [comment]
@sifraser thanks :D but I've got another problem then when I want to use coroutines...
```
fun main(args: Array<String>) = runBlocking<Unit>
```

any idea how to combine?

**Comment by xenomachina** [comment]
@GinoHereIam, you can wrap `mainBody` in `runBlocking` or vice-versa, depending on precise behavior you want. I haven't tried it, but I'm thinking it probably makes most sense to have `mainBody` on the outside, and to construct+force your parsed args object inside the `mainBody` before calling `runBlocking`. This will ensure that your arguments are parsed before starting your coroutines.

Something like this:

```
class ParsedArgs(parser: ArgParser) {
    val name by positional("The user's name").default("world")
}

fun main(args: Array<String>) = mainBody {
    val parser = ArgParser(args)
    val parsedArgs = ParsedArgs(parser)
    parser.force()

    runBlocking {
        <code that uses parsedArgs>
    }
}
```

**Comment by GinoHereIam** [comment]
sounds nice, I will try it when I am back at work. Thanks for you help. :)
