### ISSUE TITLE
ArgParser throws exceptions on --help and missing arguments

### ISSUE THREAD

**Issue by rtrietsch** [xenomachina/kotlin-argparser#37]
As the title says, ArgParser throws exceptions when requesting help and also when arguments are missing.
I'm running the compiled jar with the help command as follows:
`java -cp /path/to/myproject.jar org.company.project.Main --help`

And I'm getting the following exception:
```
Exception in thread "main" com.xenomachina.argparser.ShowHelpException: Help was requested
        at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:590)
        at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:38)
        at com.xenomachina.argparser.OptionDelegate.parseOption(OptionDelegate.kt:60)
        at com.xenomachina.argparser.ArgParser.parseLongOpt(ArgParser.kt:549)
        at com.xenomachina.argparser.ArgParser.access$parseLongOpt(ArgParser.kt:38)
        at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:473)
        at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at com.xenomachina.argparser.ArgParser.getParseOptions(ArgParser.kt)
        at com.xenomachina.argparser.ArgParser.force(ArgParser.kt:447)
        at com.xenomachina.argparser.ParsingDelegate.getValue(ParsingDelegate.kt:39)
        at com.xenomachina.argparser.ArgParser$Delegate.getValue(ArgParser.kt:340)
        at org.company.project.util.CommandLineArguments.getName(CommandLineArguments.kt)
        at org.company.project.Main.main(Main.kt:20)
```

This is my project structure:
```
.
└── org
    └── company
        ├── project
            ├── Main.kt
            └── util
                └── CommandLineArguments.kt
```

Is this expected behavior? I expect that it would show the help instructions, not an exception.

**Comment by JakeWharton** [comment]
See https://github.com/xenomachina/kotlin-argparser#error-handling

**Comment by rtrietsch** [comment]
@JakeWharton thanks, I saw that I missed the `mainBody` in my main. @xenomachina maybe it is good to make this more explicit in the readme, since this is actually part of the core functionality and it's easy to miss, since it is only stated under the _Error Handling_ section of the readme. I'll close the issue.
