### ISSUE TITLE
Exception in thread "main" com.xenomachina.argparser.ShowHelpException: Help was requested

### ISSUE THREAD

**Issue by sanity** [xenomachina/kotlin-argparser#61]
Hi, any ideas about this exception?  I thought it would print the help automatically (I passed --help as an arg).

```
Exception in thread "main" com.xenomachina.argparser.ShowHelpException: Help was requested
	at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:608)
	at com.xenomachina.argparser.ArgParser$1.invoke(ArgParser.kt:38)
	at com.xenomachina.argparser.OptionDelegate.parseOption(OptionDelegate.kt:61)
	at com.xenomachina.argparser.ArgParser.parseLongOpt(ArgParser.kt:567)
	at com.xenomachina.argparser.ArgParser.access$parseLongOpt(ArgParser.kt:38)
	at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:493)
	at com.xenomachina.argparser.ArgParser$parseOptions$2.invoke(ArgParser.kt:38)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.xenomachina.argparser.ArgParser.getParseOptions(ArgParser.kt)
	at com.xenomachina.argparser.ArgParser.force(ArgParser.kt:448)
	at com.xenomachina.argparser.ArgParser.parseInto(ArgParser.kt:470)
...
```

**Comment by JakeWharton** [comment]
https://github.com/xenomachina/kotlin-argparser#error-handling

**Comment by xenomachina** [comment]
Yes, I agree that this could've been made a bit more obvious in the documentation.

I've tweaked the "Help Formatting" section of the README. Let me know if you think there's anything else that could be done to make this more clear.
